# Generated by Django 5.2 on 2025-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_with_type', models.CharField(max_length=100)),
                ('parent_province', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_with_type', models.CharField(max_length=100)),
                ('parent_district', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=10, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tỉnh/TP'),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=10, verbose_name='Xã/Phường'),
        ),
    ]
