# Generated by Django 5.1.3 on 2025-04-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_district_ward_order_district_order_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('name_with_type', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['province__name', 'name'], 'verbose_name': 'Quận/Huyện', 'verbose_name_plural': 'Quận/Huyện'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Mặt hàng đơn hàng', 'verbose_name_plural': 'Mặt hàng đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['district__name', 'name'], 'verbose_name': 'Xã/Phường', 'verbose_name_plural': 'Xã/Phường'},
        ),
        migrations.RemoveField(
            model_name='district',
            name='parent_province',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='parent_district',
        ),
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='orders.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_with_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.district'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name_with_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='orders.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.province'),
        ),
    ]
